import "./components/burger.js";
import "./components/accordeon.js";
import "./components/slider.js";
import "./components/modal_and_valid.js";
// import "./components/file.js";
import "./components/animation.js";
import "./components/map.js";
import "./components/simplebar.js";
import "./components/select.js";
import "./components/tabs.js";
